name: Nomadic Periodical
favicon: null
layout_spectrum: 0.01074
typography_spectrum: 0.7506
title: presented by the HAVAIII Co.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5292f'
    - '#bf202b'
    - '#000000'
    - '#ff0000'
    - '#c4282f'
  brandStrength: 0.7788686896674335
  lightness: 0.843590120319277
  saturation: 0.5
  rhythmicContrast: 0.035802795784547925
purpose: []
